EXEC = run
CC = g++
CFLAGS = -c -Wall
# $(EXEC) has the value of shell variable EXEC, which is run.
# run depends on the files main.o util.o heap.o
$(EXEC) :main.o util.o heap.o

# run is created by the command g++ -o run main.o util.o
# note that the TAB before $(CC) is REQUIRED...
	$(CC) -o $(EXEC) main.o util.o heap.o

# main.o depends on the files main.h main.cpp
main.o	: main.cpp
	$(CC) $(CFLAGS) main.cpp

util.o	: util.h util.cpp
	$(CC) $(CFLAGS) util.cpp

heap.o	: heap.h heap.cpp
	$(CC) $(CFLAGS) heap.cpp

clean :
	rm *.o